---
- name: kernel option optimize
  sysctl:
    name: "{{ item.name }}" 
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  become: true
  with_items:
   - { name: 'kernel.pid_max', value: '196608' }
   - { name: 'net.ipv4.ip_forward', value: '1' }
   - { name: 'vm.max_map_count', value: '262144' }
   - { name: 'net.ipv4.neigh.default.gc_thresh1', value: '8000' }
   - { name: 'net.ipv4.neigh.default.gc_thresh2', value: '9000' }
   - { name: 'net.ipv4.neigh.default.gc_thresh3', value: '100000' }
   - { name: 'fs.inotify.max_user_watches', value: '1048576' }
   - { name: 'fs.inotify.max_user_instances', value: '8192' }
   - { name: 'net.core.somaxconn', value: '32768' }
   - { name: 'net.core.wmem_max', value: '26214400' } 
   - { name: 'net.core.rem_max', value: '26214400' }
   - { name: 'net.core.rmem_default', value: '26214400' }
   - { name: 'net.ipv4.tcp_wmem', value: '4096 12582912 16777216' }
   - { name: 'net.ipv4.tcp_rmem', value: '4096 12582912 16777216' }
   - { name: 'net.ipv4.tcp_max_syn_backlog', value: '8096' }
   - { name: 'net.ipv4.tcp_slow_start_after_idle', value: '0' }
   - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
   - { name: 'net.ipv4.conf.all.route_localnet', value: '1' }
   - { name: 'net.core.netdev_max_backlog', value: '16384' }
   - { name: 'fs.file-max', value: '2097152' }
   - { name: 'net.ipv4.ip_forward', value: '1' }
   - { name: 'fs.inotify.max_queued_events', value: '16384'}
   - { name: 'net.ipv4.conf.default.promote_secondaries', value: '1'}