- name: Gather system info 
  setup:
    filter: ansible_*

# 获取 ansible 自身变量
- name: Set common vars
  set_facts:
    ipv4_address: "{% if 'address' in ansible_default_ipv4 %}{{ansible_default_ipv4.address}}{% elsif 'ansible_'~def}"
    ipv4_interface: "{% if 'interface' in ansible_default_ipv4 %}{{ansible_default_ipv4.interface}}{% elsif 'ansible_'~def}"
    ipv4_hostname: "{{hostvars[intertory_hostname]['ansible_hostname']}}"
    centos_version: "CentOS.7.9.2009"
    pass_tigera_namespace: "tiger-operator"
    password_filename: password.yaml

- name: Set Flag After Checked
  set_fact:
    set_default_suceesss: yes